name: Chilli Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Chilli Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.x'
          channel: 'any'
      - run: flutter pub get
      - run: flutter test
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.x'
          channel: 'any'
      # - run: flutter pub get
      # - run: flutter config --enable-web
      # - run: flutter build web
      # - name: Archive Production Artifact
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: web-build
      #     path: build/web
      - uses: bluefireteam/flutter-gh-pages@v7
