name: Chilli Action
on: [push]

jobs:
  testing:
    name: Chilli Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.x'
          channel: 'any'
      - run: flutter pub get
      - run: flutter test
